# Generated by Django 5.1.1 on 2024-09-05 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fluxo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Cpf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='senha',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='senha123', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@exemplo.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Nome Padrão', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
    ]
