# Generated by Django 5.1.1 on 2024-09-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fluxo', '0006_alter_cartao_saldo_alter_saldo_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='classe',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Estudante', 'Estudante'), ('PCD', 'PCD'), ('Idoso', 'Idoso')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
