# Generated by Django 5.1.1 on 2024-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fluxo', '0007_cartao_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='classe',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Estudante', 'Estudante'), ('Especial', 'Especial'), ('Idoso', 'Idoso')], max_length=10),
        ),
    ]
